'use strict';

const { S3Client, GetObjectCommand } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');

// Reuse S3 client across requests (connection pooling)
let s3ClientInstance = null;

const getS3Client = () => {
  if (!s3ClientInstance) {
    s3ClientInstance = new S3Client({
      credentials: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
      },
      region: process.env.AWS_DEFAULT_REGION || 'auto',
      endpoint: process.env.AWS_ENDPOINT_URL,
      forcePathStyle: true,
    });
  }
  return s3ClientInstance;
};

const bucket = process.env.AWS_S3_BUCKET_NAME;
const signedUrlExpires = parseInt(process.env.AWS_SIGNED_URL_EXPIRES) || 60 * 60 * 24 * 7; // Default 7 days

// In-memory cache for signed URLs
// Key: S3 key, Value: { signedUrl, expiresAt }
const signedUrlCache = new Map();

// Cache URLs for slightly less time than they're valid (95% of expiry time)
// This ensures cached URLs are always valid when returned
const CACHE_BUFFER_RATIO = 0.95;

/**
 * Get a signed URL from cache or generate a new one
 */
const getCachedSignedUrl = async (s3Client, key) => {
  const now = Date.now();
  const cached = signedUrlCache.get(key);

  // Return cached URL if still valid
  if (cached && cached.expiresAt > now) {
    return cached.signedUrl;
  }

  // Generate new signed URL
  const command = new GetObjectCommand({
    Bucket: bucket,
    Key: key,
  });

  const signedUrl = await getSignedUrl(s3Client, command, {
    expiresIn: signedUrlExpires,
  });

  // Cache the new URL
  const cacheExpiresIn = signedUrlExpires * CACHE_BUFFER_RATIO * 1000; // Convert to ms
  signedUrlCache.set(key, {
    signedUrl,
    expiresAt: now + cacheExpiresIn,
  });

  // Periodically clean up expired entries (every 100 cache sets)
  if (signedUrlCache.size % 100 === 0) {
    cleanupExpiredCache();
  }

  return signedUrl;
};

/**
 * Remove expired entries from cache
 */
const cleanupExpiredCache = () => {
  const now = Date.now();
  for (const [key, value] of signedUrlCache.entries()) {
    if (value.expiresAt <= now) {
      signedUrlCache.delete(key);
    }
  }
};

// ---------------------------------------------------------------------------
// Key validation
//
// The signed-url endpoints are public (auth: false). Without validation they
// act as a signing oracle for ANY object in the private bucket. Before signing
// we therefore verify that the requested key corresponds to a real Strapi
// upload (plugin::upload.file), including responsive format variants
// (thumbnail_/small_/medium_/large_/xlarge_ prefixed keys generated by the
// upload plugin — see config/plugins.js breakpoints).
// ---------------------------------------------------------------------------

// Format prefixes = configured breakpoints in config/plugins.js + Strapi's
// built-in thumbnail format. Format files are named `${format}_${hash}${ext}`.
const FORMAT_PREFIXES = ['thumbnail', 'small', 'medium', 'large', 'xlarge'];
const FORMAT_PREFIX_RE = new RegExp(`^(${FORMAT_PREFIXES.join('|')})_(.+)$`);

// Conservative allowlist for S3 keys as produced by the upload provider:
// `${path}/${hash}${ext}` where hash/ext are alphanumeric with . _ -
// Rejects anything with backslashes, colons, spaces, control chars, etc.
const SAFE_KEY_RE = /^[A-Za-z0-9][A-Za-z0-9._/-]*$/;
const MAX_KEY_LENGTH = 512;

/**
 * Returns true if the key is structurally safe (no traversal, no absolute
 * paths, no empty/dot segments, allowlisted characters only).
 */
const isSafeKey = (key) => {
  if (typeof key !== 'string' || key.length === 0 || key.length > MAX_KEY_LENGTH) {
    return false;
  }
  if (!SAFE_KEY_RE.test(key)) {
    return false;
  }
  // No empty, '.' or '..' path segments (SAFE_KEY_RE already rejects a
  // leading '/', this rejects 'a//b', 'a/../b', 'a/./b', trailing '/').
  const segments = key.split('/');
  for (const segment of segments) {
    if (segment === '' || segment === '.' || segment === '..') {
      return false;
    }
  }
  return true;
};

/**
 * Extract the S3 key from various URL formats.
 * Accepts:
 *   - a bare key:               "Christmas_Tree_47f57970a1.png"
 *   - a rooted path:            "/Christmas_Tree_47f57970a1.png"
 *   - a full http(s) URL:       "https://storage.railway.app/<bucket>/<key>"
 * Returns null for anything unsafe (path traversal, protocol-relative URLs,
 * non-http(s) schemes, disallowed characters).
 */
const extractKeyFromUrl = (url) => {
  if (!url || typeof url !== 'string') return null;

  let candidate = url.trim();

  if (candidate.startsWith('http://') || candidate.startsWith('https://')) {
    try {
      const urlObj = new URL(candidate);
      // Percent-decode so encoded traversal (%2e%2e) is caught by isSafeKey
      candidate = decodeURIComponent(urlObj.pathname);
    } catch (e) {
      return null;
    }
  } else if (candidate.includes('://') || candidate.startsWith('//')) {
    // Non-http(s) scheme or protocol-relative URL — reject outright
    return null;
  }

  // Remove leading slash(es)
  candidate = candidate.replace(/^\/+/, '');

  // If the path includes the bucket name, remove it
  if (bucket && candidate.startsWith(bucket + '/')) {
    candidate = candidate.slice(bucket.length + 1);
  }

  return isSafeKey(candidate) ? candidate : null;
};

// Short-lived in-memory cache of keys already validated against the DB, so
// hot images don't hit Postgres on every request. Positive results only.
const validKeyCache = new Map(); // key -> expiresAt (ms epoch)
const VALID_KEY_CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes
const VALID_KEY_CACHE_MAX = 5000;

const rememberValidKey = (key) => {
  if (validKeyCache.size >= VALID_KEY_CACHE_MAX) {
    // Drop expired entries; if still full, drop the oldest inserted
    const now = Date.now();
    for (const [k, expiresAt] of validKeyCache.entries()) {
      if (expiresAt <= now) validKeyCache.delete(k);
    }
    if (validKeyCache.size >= VALID_KEY_CACHE_MAX) {
      const oldest = validKeyCache.keys().next().value;
      validKeyCache.delete(oldest);
    }
  }
  validKeyCache.set(key, Date.now() + VALID_KEY_CACHE_TTL_MS);
};

/**
 * Split a key into { dir, stem, ext } where key = dir + stem + ext,
 * dir includes the trailing '/' (or '' if none) and ext includes the dot.
 */
const splitKey = (key) => {
  const slashIdx = key.lastIndexOf('/');
  const dir = slashIdx >= 0 ? key.slice(0, slashIdx + 1) : '';
  const base = slashIdx >= 0 ? key.slice(slashIdx + 1) : key;
  const dotIdx = base.lastIndexOf('.');
  const stem = dotIdx > 0 ? base.slice(0, dotIdx) : base;
  const ext = dotIdx > 0 ? base.slice(dotIdx) : '';
  return { dir, stem, ext };
};

/**
 * Returns true if `key` corresponds to a real Strapi upload — either an
 * original file (matched on stored url, or on hash+ext for legacy rows that
 * stored a full URL) or one of its generated format variants.
 */
const isKnownUploadKey = async (key) => {
  const cachedExpiry = validKeyCache.get(key);
  if (cachedExpiry && cachedExpiry > Date.now()) {
    return true;
  }

  const fileQuery = strapi.db.query('plugin::upload.file');
  const { stem, ext } = splitKey(key);

  // 1) Original file: provider stores the raw key in `url`; also match on
  //    hash+ext in case older rows stored a rooted path or full URL.
  const original = await fileQuery.findOne({
    select: ['id'],
    where: {
      $or: [{ url: key }, { hash: stem, ext }],
    },
  });
  if (original) {
    rememberValidKey(key);
    return true;
  }

  // 2) Format variant: `${format}_${parentHash}${ext}` — find the parent by
  //    hash and confirm it actually has that generated format.
  const formatMatch = stem.match(FORMAT_PREFIX_RE);
  if (!formatMatch) {
    return false;
  }
  const [, formatName, parentHash] = formatMatch;

  const parent = await fileQuery.findOne({
    select: ['id', 'formats'],
    where: { hash: parentHash },
  });
  if (!parent || !parent.formats) {
    return false;
  }

  // A format matches on its stored hash or url. Deliberately no ext-equality
  // requirement: Strapi can normalize extensions on generated variants, which
  // would false-reject real keys, and the hash (name_random) is already
  // unguessable - signing a wrong-ext key just yields a URL that S3 404s.
  const matchesFormat = (f) =>
    Boolean(f) &&
    (f.hash === stem || f.url === key || extractKeyFromUrl(f.url) === key);

  const isRealFormat =
    matchesFormat(parent.formats[formatName]) ||
    // Fallback: match any stored format, in case the breakpoint name embedded
    // in the key doesn't line up with the formats map key (renamed breakpoints)
    Object.values(parent.formats).some(matchesFormat);

  if (isRealFormat) {
    rememberValidKey(key);
    return true;
  }
  return false;
};

module.exports = {
  /**
   * Generate a signed URL for a single file
   * POST /api/signed-url
   * Body: { url: "filename.png" } or { url: "https://..." }
   */
  async getSignedUrl(ctx) {
    try {
      const { url } = ctx.request.body;

      if (!url) {
        return ctx.badRequest('URL is required');
      }

      const key = extractKeyFromUrl(url);

      if (!key) {
        return ctx.badRequest('Could not extract file key from URL');
      }

      if (!(await isKnownUploadKey(key))) {
        return ctx.notFound('File not found');
      }

      const s3Client = getS3Client();
      const signedUrl = await getCachedSignedUrl(s3Client, key);

      // Set cache headers so frontend/CDN can cache the response
      // Cache for 1 hour on client, allow CDN to cache for longer
      ctx.set('Cache-Control', 'public, max-age=3600, s-maxage=86400');

      return {
        url: signedUrl,
        expiresIn: signedUrlExpires,
      };
    } catch (error) {
      strapi.log.error('Error generating signed URL:', error);
      return ctx.internalServerError('Failed to generate signed URL');
    }
  },

  /**
   * Generate signed URLs for multiple files
   * POST /api/signed-urls
   * Body: { urls: ["filename1.png", "filename2.png"] }
   */
  async getSignedUrls(ctx) {
    try {
      const { urls } = ctx.request.body;

      if (!urls || !Array.isArray(urls)) {
        return ctx.badRequest('URLs array is required');
      }

      if (urls.length > 100) {
        return ctx.badRequest('Too many URLs (max 100)');
      }

      const s3Client = getS3Client();
      const results = await Promise.all(
        urls.map(async (url) => {
          try {
            const key = extractKeyFromUrl(url);
            if (!key) {
              return { original: url, error: 'Could not extract key' };
            }
            if (!(await isKnownUploadKey(key))) {
              return { original: url, error: 'File not found' };
            }
            const signedUrl = await getCachedSignedUrl(s3Client, key);
            return { original: url, signedUrl };
          } catch (error) {
            return { original: url, error: error.message };
          }
        })
      );

      // Set cache headers for batch endpoint
      ctx.set('Cache-Control', 'public, max-age=3600, s-maxage=86400');

      return {
        urls: results,
        expiresIn: signedUrlExpires,
      };
    } catch (error) {
      strapi.log.error('Error generating signed URLs:', error);
      return ctx.internalServerError('Failed to generate signed URLs');
    }
  },

  /**
   * GET endpoint for signed URL - more CDN-friendly
   * GET /api/signed-url/:key
   * Example: GET /api/signed-url/Christmas_Tree_47f57970a1.png
   *
   * This endpoint can be cached by CDNs and browsers more easily
   */
  async getSignedUrlByKey(ctx) {
    try {
      const { key } = ctx.params;

      if (!key) {
        return ctx.badRequest('Key is required');
      }

      // Decode the key in case it was URL-encoded, then re-validate
      let decodedKey;
      try {
        decodedKey = decodeURIComponent(key);
      } catch (e) {
        return ctx.badRequest('Invalid key encoding');
      }

      const safeKey = extractKeyFromUrl(decodedKey);
      if (!safeKey) {
        return ctx.badRequest('Invalid key');
      }

      if (!(await isKnownUploadKey(safeKey))) {
        return ctx.notFound('File not found');
      }

      const s3Client = getS3Client();
      const signedUrl = await getCachedSignedUrl(s3Client, safeKey);

      // More aggressive caching for GET requests (CDN-friendly)
      ctx.set('Cache-Control', 'public, max-age=3600, s-maxage=86400, stale-while-revalidate=86400');

      return {
        url: signedUrl,
        expiresIn: signedUrlExpires,
      };
    } catch (error) {
      strapi.log.error('Error generating signed URL by key:', error);
      return ctx.internalServerError('Failed to generate signed URL');
    }
  },

  /**
   * Image proxy/redirect endpoint - MOST performant for direct img src usage
   * GET /api/image/:key
   * Example: <img src="https://api.pfrastro.com/api/image/Christmas_Tree_47f57970a1.png" />
   *
   * Redirects directly to the signed S3 URL - eliminates one round trip!
   * The browser will cache the redirect and follow it directly.
   */
  async redirectToSignedUrl(ctx) {
    try {
      const { key } = ctx.params;

      if (!key) {
        return ctx.badRequest('Key is required');
      }

      // Decode the key in case it was URL-encoded, then re-validate
      let decodedKey;
      try {
        decodedKey = decodeURIComponent(key);
      } catch (e) {
        return ctx.badRequest('Invalid key encoding');
      }

      const safeKey = extractKeyFromUrl(decodedKey);
      if (!safeKey) {
        return ctx.badRequest('Invalid key');
      }

      if (!(await isKnownUploadKey(safeKey))) {
        return ctx.notFound('File not found');
      }

      const s3Client = getS3Client();
      const signedUrl = await getCachedSignedUrl(s3Client, safeKey);

      // Cache the redirect for 1 hour
      ctx.set('Cache-Control', 'public, max-age=3600, s-maxage=86400');

      // 302 redirect to the signed URL
      ctx.redirect(signedUrl);
    } catch (error) {
      strapi.log.error('Error redirecting to signed URL:', error);
      return ctx.internalServerError('Failed to redirect to signed URL');
    }
  },
};
